-- vim.opt.clipboard = "unnamedplus"                              -- allows neovim to access the system clipboard
vim.o.cmdheight = 1 -- more space in the neovim command line for displaying messages
vim.o.winborder = 'rounded'
-- vim.o.completeopt = { "menu", "menuone", "noselect" }
vim.o.conceallevel = 0                                       -- so that `` is visible in markdown files
-- vim.opt.fileencoding = "utf-8"                                 -- the encoding written to a file
vim.o.hlsearch = false                                       -- highlight all matches on previous search pattern
vim.o.incsearch = true                                       -- show search matches incrementally
vim.o.ignorecase = true                                      -- ignore case in search patterns
vim.o.mouse = "a"                                            -- allow the mouse to be used in neovim
vim.o.pumheight = 10                                         -- pop up menu height
vim.o.showmode = false                                       -- we don't need to see things like -- INSERT -- anymore
vim.o.showtabline = 0                                        -- never show tabs
vim.o.smartcase = true                                       -- smart case
vim.o.smartindent = true                                     -- make indenting smarter again
vim.o.relativenumber = true                                  -- turn on relative line numbering
vim.o.splitbelow = true                                      -- force all horizontal splits to go below current window
vim.o.splitright = true                                      -- force all vertical splits to go to the right of current window
vim.o.swapfile = false                                       -- creates a swapfile
vim.o.termguicolors = true                                   -- set term gui colors (most terminals support this)
vim.o.timeoutlen = 1000                                      -- time to wait for a mapped sequence to complete (in milliseconds)
vim.o.undodir = os.getenv("HOME") .. "/.config/nvim/undodir" -- set an undo directory
vim.o.undofile = true                                        -- enable persistent undo
vim.o.updatetime = 250                                       -- faster completion (4000ms default)
vim.o.backup = false                                         -- if a file is being edited by another program (or was written to file while editing with another program), it is not allowed to be edited
vim.o.expandtab = true                                       -- convert tabs to spaces
vim.o.shiftwidth = 4                                         -- the number of spaces inserted for each indentation
vim.o.tabstop = 4                                            -- insert 2 spaces for a tab
vim.o.cursorline = true                                      -- highlight the current line
vim.o.number = true                                          -- set numbered lines
vim.o.laststatus = 3
vim.o.showcmd = false
vim.o.ruler = false
vim.o.numberwidth = 4 -- set number column width to 2 {default 4}
vim.o.signcolumn = "yes"
vim.o.wrap = false    -- display lines as one long line
vim.o.scrolloff = 8   -- is one of my fav
vim.o.sidescrolloff = 8
vim.o.fillchars = "eob:~"
vim.opt.shortmess:append("c")
vim.opt.whichwrap:append("<,>,[,],h,l")
vim.opt.iskeyword:append("-")
vim.g.netrw_broptwse_split = 0
vim.g.netrw_banner = 0
vim.g.netrw_winsize = 25
vim.o.colorcolumn = "80"
