require("mfaris.plugin-config.alpha")
require('mfaris.plugin-config.autocommands')
-- require('mfaris.plugin-config.autopairs')
require('mfaris.plugin-config.bufferline')
require('mfaris.plugin-config.comment')
require('mfaris.plugin-config.gitsigns')
require('mfaris.plugin-config.illuminate')
require('mfaris.plugin-config.impatient')
require('mfaris.plugin-config.indentline')
require('mfaris.plugin-config.impatient')
require('mfaris.plugin-config.lualine')
require('mfaris.plugin-config.luasnip')
require("mfaris.plugin-config.project")
require("mfaris.plugin-config.telescope")
-- require("mfaris.plugin-config.toggleterm")
require("mfaris.plugin-config.treesitter")
require("mfaris.plugin-config.undotree")
-- require('mfaris.plugin-config.leap')
require('mfaris.plugin-config.null-ls')
require('mfaris.plugin-config.copilot')
require('mfaris.plugin-config.dap')
